scrape_configs:
  - job_name: "mybank-app"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["mybank:9001"]
  - job_name: "mysql"
    scrape_interval: 5s
    static_configs:
      - targets: ["dbexporter:9104"]
